### ISSUE TITLE
MFCC12EDA.csv is not reaching the row of 4457391

### ISSUE THREAD

**Issue by Haorotu** [david-yoon/multimodal-speech-emotion#3]
Hello David:
Thank you very much for enjoying your code. When I run the IEMOCAP_01_wav_to_feature.ipynb in the Preprocessing folder. I only got a .wav 's MFCC coefficient like 599,that isn't reaching the 4457391,I didn't know how to solve it. Please help me ,thanks very much.

Best wishes!

**Comment by david-yoon** [comment]
Hi,
I just cloned the repository and tested the "IEMOCAP_01_wav_to_feature.ipynb". 
For my case, it processed the MFCC coefficient properly and generated 4,457,391 lines of samples as belows:


![image](https://user-images.githubusercontent.com/13551317/55665645-9165c400-587e-11e9-9d6d-60e8fcf4f83b.png)



some quick questions are
- do you properly installed "opensmile" toolkit
- do you have following directory in path?  "./data/processed/IEMOCAP/
- do you put the IEMOCAP dataset as follows?:  "./data/raw/IEMOCAP_full_release"

If you still have the problems, let me know it. We'll find the solution.
Thank you

**Comment by Haorotu** [comment]
Hi David:
Firstly, thanks very much  for helping me to check the question, but this question still arises. When I use the MFCC12E_D_A_Z.config to extract features, it can be right to get the 4457391 lines, but use the MFCC12E_D_A.config that only gets a file of feature that is 599. 599 means the last file and every ".wav" file is covered by previous file.

I have another problem to hope you help me. I only think of the audio not text(NLP). When I use MFCC12E_D_A_Z.config to get the result to train the model that I use the train_audio.py, the result is very bad.
![image](https://user-images.githubusercontent.com/28502249/55694428-c0974500-59e6-11e9-92ee-5ffe9d0dd736.png)
Please give me some suggestion about model, thanks very much.

Best wishes!

**Comment by david-yoon** [comment]
Hi,

I tested the preprocessing codes with both cases,

1. MFCC12E_D_A.config
- In my case, it properly generated the audio features (4,457,391)
- results:
2019-04-09 09:23	audio_woZ_set01	SE_prosody_Daudio_woZ_set01_b128_es750_L1_H200_dr0.7_04-09-09-12	0.5718849840255591	0.5705045278137129
2019-04-09 09:25	audio_woZ_set01	SE_nlp_Daudio_woZ_set01_b128_es128_L1_H200_G1_dr0.3_04-09-09-23	0.6549520766773163	0.6649417852522639
2019-04-09 09:32	audio_woZ_set01	SE_multi_Daudio_woZ_set01_b128_esA750_LA1_HA200_drA0.7_esT128_LT1_HT200_G1_drT0.3_04-09-09-25	0.7539936102236422	0.7580853816300129


2. MFCC12E_D_A_Z.config
- In my case, it also properly generated the audio features (4,457,391)
- results:
2019-04-10 15:45	audio_woZ_set01	SE_prosody_Daudio_woZ_set01_b128_es750_L1_H200_dr0.7_04-10-15-39	0.5047923322683706	0.48641655886157825
2019-04-10 15:47	audio_woZ_set01	SE_nlp_Daudio_woZ_set01_b128_es128_L1_H200_G1_dr0.3_04-10-15-45	0.6517571884984026	0.6532988357050453
2019-04-10 15:51	audio_woZ_set01	SE_multi_Daudio_woZ_set01_b128_esA750_LA1_HA200_drA0.7_esT128_LT1_HT200_G1_drT0.3_04-10-15-47	0.6869009584664537	0.7115135834411385


As you pointed out, I also got a lower result with "MFCC12E_D_A_Z" audio features than that of the "MFCC12E_D_A" audio feature case.

I mainly performed the experiment with the "MFCC12E_D_A" features, so it seems that "MFCC12E_D_A_Z"  case may require another hyper-parameter search to get the best performance.

For your case, I cannot explain why your environment did not generate "MFCC12E_D_A" audio features properly. One guess is due to a difference in the opensmile version?

Anyway, if you need the preprocessed dataset ("MFCC12E_D_A" audio features) directly from me, please send me an email that shows you've got an IEMOCAP licence from IEMOCAP team.

Thank you :)

**Comment by hai19991331** [comment]
hi i can't find MFCC12EDA.csv 
I've run this command but it didn't create MFCC12EDA.csv file
![image](https://user-images.githubusercontent.com/40104081/69042805-736f5d00-0a24-11ea-8ea5-63a60073103f.png)

**Comment by WaNePr** [comment]
> Hi David:
> Firstly, thanks very much for helping me to check the question, but this question still arises. When I use the MFCC12E_D_A_Z.config to extract features, it can be right to get the 4457391 lines, but use the MFCC12E_D_A.config that only gets a file of feature that is 599. 599 means the last file and every ".wav" file is covered by previous file.
> 
> I have another problem to hope you help me. I only think of the audio not text(NLP). When I use MFCC12E_D_A_Z.config to get the result to train the model that I use the train_audio.py, the result is very bad.
> ![image](https://user-images.githubusercontent.com/28502249/55694428-c0974500-59e6-11e9-92ee-5ffe9d0dd736.png)
> Please give me some suggestion about model, thanks very much.
> 
> Best wishes!

I also encouter the problem as shown in your pic, where test result can become zeros during inference. Do you know how to solve it ?

**Comment by YJY-0718** [comment]
Hello David:
When I run the IEMOCAP_01_wav_to_feature.ipynb in the Preprocessing folder. I only got a .wav 's MFCC coefficient like 599,that isn't reaching the 4457391,I didn't know how to solve it. And I've seen people ask this question, and I'd like to know how you  finally worked it out.I also read some of the questions you asked. I installed Opensmile2.3.0 and got permission from the IEMOCAP team to place the raw/IEMOCAP_full_release correctly.

Errors'ValueError: cannot copy sequence with size 0 to array axis with dimension 35' were also made in dealing with prosodic features.

I hope you can give me some ideas to correct this mistake
Thank you very much

**Comment by david-yoon** [comment]
> Hello David:
> When I run the IEMOCAP_01_wav_to_feature.ipynb in the Preprocessing folder. I only got a .wav 's MFCC coefficient like 599,that isn't reaching the 4457391,I didn't know how to solve it. And I've seen people ask this question, and I'd like to know how you finally worked it out.I also read some of the questions you asked. I installed Opensmile2.3.0 and got permission from the IEMOCAP team to place the raw/IEMOCAP_full_release correctly.
> 
> Errors'ValueError: cannot copy sequence with size 0 to array axis with dimension 35' were also made in dealing with prosodic features.
> 
> I hope you can give me some ideas to correct this mistake
> Thank you very much


Hi,

Unfortunately, most of the previously asked questions were solved by themselves. I tested the Jupyter code by myself and found that I can generate the exact size of the data. 

I expect the issues were originated from the environmental issues ( library or hardware version) since there are also people who successfully generate the data. 

If you just need the final dataset, you may use the released preprocessed dataset from my Github. 
If you have other purposes of extracting MFCC features, please let me know that.

Thank you,
David

**Comment by YJY-0718** [comment]
Hello 
I would like to know which version of OpenSmile you installed, so that I can check whether the problem I have is related to its version.In addition, I would like to know the specific environment that you need for the entire program, not just the environment requirements that are included in the README.
Thank you very much

**Comment by trungkien110298** [comment]
You can fix this problem by set append option in file share/standard_data_output_lldonly.conf.inc to 1

> append = \cm[appendcsv{1}:set to 1 to append to the LLD output csv file, default is not to append]
