### ISSUE TITLE
Wav files dataset

### ISSUE THREAD

**Issue by Tensorflow13** [david-yoon/multimodal-speech-emotion#5]
Hi David, i'm doing a multimodal-sentiment-analysis in speech data so I wanted to know if its possible that you send me your raw wav files dataset via google drive or a repo?

**Comment by david-yoon** [comment]
Hi, 

If you mean the original IEMOCAP dataset (including raw wav files), please contact the IEMOCAP team to receive the data with the license.
link: https://sail.usc.edu/iemocap/

If you need preprocessed files that I used in the experiments, please forward me the mail from IEMOCAP team so that I will be aware of the license given to you. Then I can share you the preprocessed files.

Thank you,
David
