### ISSUE TITLE
No such file or directory: './data/processed/IEMOCAP/MFCC12EDA.csv'

### ISSUE THREAD

**Issue by hai19991331** [david-yoon/multimodal-speech-emotion#6]
Hi david 
I've run the following code but it don't create MFCC12EDA.csv file 
![image](https://user-images.githubusercontent.com/40104081/69046842-80904a00-0a2c-11ea-8f60-e8fbb83deb7e.png)

Thanks you for your help

**Comment by david-yoon** [comment]
Hi,
It seems that the OPENSmile software is not properly installed in your environments, thus, the out_file was not generated.
Just before the cell (shown in the figure), there exists a part to set the path of the installed OPENSmile. Please check whether it is properly set.

From the experience (previous issues reported in the repository), it is quite hard for me to give a guide for the software installation due to the differences in the system environments.
 
If the pre-processed corpus will help your investigation, please drop me an email with the IEMOCAP license. I'll provide you with the pre-processed corpus for the experiments!
(mail: mysmilesh@gmail.com)

Thank you,
David

**Comment by pri310** [comment]
Hii do any one have IEMOCAP database to download .. i have seen under a website but it gives large files including others .. so do any have IEMOCAP alone .. please do send me the link.

**Comment by david-yoon** [comment]
Hi,
You may ask the IEMOCAP team for the original dataset.
https://sail.usc.edu/iemocap/

**Comment by pri310** [comment]
thank you!!! and can you please tell me whether is it audio only file and what language used and how many total files are used????
